# Generated by Django 5.2 on 2025-06-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fooddonation_delete_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='food_photos/'),
        ),
    ]
