# Generated by Django 5.2 on 2025-06-02 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fooddonation_assigned_to_fooddonation_delivered_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picked_up', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('picked_time', models.DateTimeField(blank=True, null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.fooddonation')),
            ],
        ),
    ]
