# Generated by Django 5.2 on 2025-06-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fooddonation',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='fooddonation',
            name='picked_up',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
