# Generated by Django 5.2 on 2025-06-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('ngo', 'NGO'), ('delivery', 'Delivery Personnel')], max_length=20),
        ),
    ]
